In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r'D:\STUDY MATERIAL\finaldashboard - Copy\data.xlsx',sheet_name = 'Sheet2')
df['Start Month']=df['Start Date'].dt.month
df['End Month']=df['End Date'].dt.month
df['End Year']=df['End Date'].dt.year
df['Start Year']=df['Start Date'].dt.year
df['Start Month']= df['Start Month'].replace({1:'January',2:'February',3:'March',4:'April',5:'May',6:'June',7:'July',8:'August',9:'September',10:'October',11:'November',12:'December'})
df['End Month']= df['End Month'].replace({1:'January',2:'February',3:'March',4:'April',5:'May',6:'June',7:'July',8:'August',9:'September',10:'October',11:'November',12:'December'})

In [3]:
df

,Item Code,Description,Start Date,End Date,Days to Complete,Responsible Party,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Start Month,End Month,End Year,Start Year
0,1/23/1.1,water leak,2019-01-23,2019-01-23,1.0,GC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,January,January,2019,2019
1,1/23/1.2,cafeteria demo,2019-01-23,2019-01-23,1.0,GC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,January,January,2019,2019
2,1/23/1.3,elevator,2019-01-23,2019-02-11,19.0,O,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,January,February,2019,2019
3,1/23/2.1,bids due,2019-01-23,2019-02-11,19.0,GC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,January,February,2019,2019
4,1/23/2.2,Bulletin #1,2019-01-23,2019-01-23,1.0,GC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,January,January,2019,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,11/6/5.47,287 Conduit for AV,2019-11-06,2019-11-09,3.0,D,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,November,November,2019,2019
339,11/6/7.100,Electrical shutdown,2019-11-06,2019-11-09,3.0,GC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,November,November,2019,2019
340,11/6/7.101,Duct detectors,2019-11-06,2019-11-15,9.0,D,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,November,November,2019,2019
341,11/6/7.102,Elevator finishes,2019-11-06,2019-11-15,9.0,GC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,November,November,2019,2019
342,11/6/7.103,Acoustic sound panels,2019-11-06,2019-11-09,3.0,GC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,November,November,2019,2019